# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190418_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.CharField(max_length=100, verbose_name='评论目标网址'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(default='1.com', verbose_name='网站'),
        ),
    ]
